/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef NODEJSSTART_H
#define NODEJSSTART_H

/* function declarations */
void init_nodejsStart(void);
Netsnmp_Node_Handler handle_nodejsStart;

#endif /* NODEJSSTART_H */
